// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebChatApi;

namespace WebChatApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220328202700_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebChatApi.Entidades.Mensaje", b =>
                {
                    b.Property<int>("MensajeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MensajeChat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("UId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioUId")
                        .HasColumnType("int");

                    b.HasKey("MensajeId");

                    b.HasIndex("UsuarioUId");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("WebChatApi.Entidades.Usuario", b =>
                {
                    b.Property<int>("UId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("WebChatApi.Entidades.Mensaje", b =>
                {
                    b.HasOne("WebChatApi.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioUId");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
